apiVersion: v1
kind: PersistentVolume
metadata:
    name: "..."
spec:
    capacity:
        storage: 5Ki
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    storageClassName: manual
    hostPath:
        path: "/certificate"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: "k8s-ca-certificates"
spec:
    storageClassName: manual
    resources:
        requests:
            storage: 5Ki
    accessModes:
        - ReadWriteMany
