name: Build a docker container and push it to Dockerhub

on:
    workflow_call:
        inputs:
            container:
                required: true
                type: string
        secrets:
            DOCKER_HUB_USERNAME:
                required: true
            DOCKER_HUB_PASSWORD:
                required: true

jobs:
    build-container:
        runs-on: ubuntu-latest
        steps:
            - name: Choose correct docker hub tag
              run: |
                  if [[ $GITHUB_REF_NAME == 'main' ]]; then
                      echo "DOCKER_TAG=$latest" >> "$GITHUB_ENV"
                  else
                      echo "DOCKER_TAG=$GITHUB_REF_NAME" >> "$GITHUB_ENV"
                  fi

            - name: Clone repository
              uses: actions/checkout@v2
              with:
                  branch: "$GITHUB_REF_NAME"

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            - name: Debug
              run: |
                  ls -la .
                  echo 
                  ls -la ./containers
                  echo 
                  ls -la ./containers/${{ inputs.container }}

            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: ./containers/${{ inputs.container }}
                  file: ./containers/${{ inputs.container }}/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/k8s_ca-${{ inputs.container }}:${{ env.DOCKER_TAG }}
